#game settings
RES = WIDTH, HEIGHT = 1600,900
FPS = 60
SCROLL_SPEED = 8

#bird
BIRD_POS = WIDTH // 4 , HEIGHT // 3
BIRD_SCALE = 1.5
BIRD_ANIMATION_TIMER = 150
BIRD_JUMP = -16
BIRD_ANGLE = 25

#ground
GROUND_HEIGHT = HEIGHT // 12
GROUND_Y = HEIGHT - GROUND_HEIGHT

#physics
GRAVITY = 1

#pipes
PIPES_WIDTH = 250
PIPES_HEIGHT = HEIGHT
DIST_BETWEEN_PIPES = 650
GAP_HEIGHT = 320
HALF_GAP_BETWEEN_PIPES = GAP_HEIGHT // 2

# fire
STEPS_BETWEEN_COLORS_MENU = 12
STEPS_BETWEEN_COLORS_GAME = 5
COLORS = ['black', 'red', 'orange', 'yellow', 'white']
PIXEL_SIZE = 4
FIRE_REPS = 4
FIRE_WIDTH = WIDTH // (PIXEL_SIZE * FIRE_REPS)
FIRE_HEIGHT = HEIGHT // PIXEL_SIZE

# menu 
MENU_POS = WIDTH // 11 , HEIGHT // 4
MENU_RES = WIDTH // 1.2, HEIGHT // 4

# score
HG_file = 'highscore.txt'