RES = WIDTH, HEIGHT = 1600, 900
FPS = 60
SCROLL_SPEED = 8

# bird
BIRD_POS = WIDTH // 4, HEIGHT // 4
BIRD_SCALE = 1.5
BIRD_AN = 150
GRAVITY = 1
JUMP = -16
BIRD_ANGLE = 25

# ground
GROUND_HEIGHT = HEIGHT // 12
GROUND_Y = HEIGHT - GROUND_HEIGHT

# pipes
PIPES_WIDTH = 150
PIPES_HEIGHT = HEIGHT
DIST_BETWEEN_PIPES = 650
GAP_HEIGHT = 320
HALF_GAP_BETWEEN_PIPES = GAP_HEIGHT // 2
